// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'f5f01b3ce810b5dcef48be6d6edf2064f7e8db784f24e707653a31358e6f3ff9'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Campanha: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly instanciaId: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly emailRelatorio: CodecTypes['pg/text@1']['output'] | null;
      readonly status:
        'rascunho' | 'em_andamento' | 'pausada' | 'concluida' | 'cancelada' | 'falhou';
      readonly hashTokenAcesso: CodecTypes['pg/text@1']['output'] | null;
      readonly iniciadaEm: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly finalizadaEm: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly criadaEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly CampanhaContato: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly campanhaId: CodecTypes['pg/int4@1']['output'];
      readonly contatoId: CodecTypes['pg/int4@1']['output'];
      readonly status: 'pendente' | 'processando' | 'concluido' | 'parcial' | 'falhou';
      readonly iniciadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly finalizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Contato: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly telefone: CodecTypes['pg/text@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Instancia: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly usuarioUzapi: CodecTypes['pg/text@1']['output'];
      readonly token: CodecTypes['pg/text@1']['output'];
      readonly idNumeroTelefone: CodecTypes['pg/text@1']['output'];
      readonly limiteDiarioContatos: CodecTypes['pg/int4@1']['output'];
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Mensagem: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly campanhaId: CodecTypes['pg/int4@1']['output'];
      readonly posicao: CodecTypes['pg/int4@1']['output'];
      readonly tipo: 'texto' | 'imagem' | 'audio';
      readonly texto: CodecTypes['pg/text@1']['output'] | null;
      readonly urlMidia: CodecTypes['pg/text@1']['output'] | null;
      readonly criadaEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly ResultadoMensagem: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly mensagemId: CodecTypes['pg/int4@1']['output'];
      readonly campanhaContatoId: CodecTypes['pg/int4@1']['output'];
      readonly status: 'pendente' | 'sucesso' | 'falhou';
      readonly idFila: CodecTypes['pg/text@1']['output'] | null;
      readonly idMensagem: CodecTypes['pg/text@1']['output'] | null;
      readonly erro: CodecTypes['pg/text@1']['output'] | null;
      readonly enviadaEm: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly criadaEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Campanha: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly instanciaId: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly emailRelatorio: CodecTypes['pg/text@1']['input'] | null;
      readonly status:
        'rascunho' | 'em_andamento' | 'pausada' | 'concluida' | 'cancelada' | 'falhou';
      readonly hashTokenAcesso: CodecTypes['pg/text@1']['input'] | null;
      readonly iniciadaEm: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly finalizadaEm: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly criadaEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly CampanhaContato: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly campanhaId: CodecTypes['pg/int4@1']['input'];
      readonly contatoId: CodecTypes['pg/int4@1']['input'];
      readonly status: 'pendente' | 'processando' | 'concluido' | 'parcial' | 'falhou';
      readonly iniciadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly finalizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Contato: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly telefone: CodecTypes['pg/text@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Instancia: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly usuarioUzapi: CodecTypes['pg/text@1']['input'];
      readonly token: CodecTypes['pg/text@1']['input'];
      readonly idNumeroTelefone: CodecTypes['pg/text@1']['input'];
      readonly limiteDiarioContatos: CodecTypes['pg/int4@1']['input'];
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Mensagem: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly campanhaId: CodecTypes['pg/int4@1']['input'];
      readonly posicao: CodecTypes['pg/int4@1']['input'];
      readonly tipo: 'texto' | 'imagem' | 'audio';
      readonly texto: CodecTypes['pg/text@1']['input'] | null;
      readonly urlMidia: CodecTypes['pg/text@1']['input'] | null;
      readonly criadaEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly ResultadoMensagem: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly mensagemId: CodecTypes['pg/int4@1']['input'];
      readonly campanhaContatoId: CodecTypes['pg/int4@1']['input'];
      readonly status: 'pendente' | 'sucesso' | 'falhou';
      readonly idFila: CodecTypes['pg/text@1']['input'] | null;
      readonly idMensagem: CodecTypes['pg/text@1']['input'] | null;
      readonly erro: CodecTypes['pg/text@1']['input'] | null;
      readonly enviadaEm: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly criadaEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly campanha: {
      readonly criadaEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly emailRelatorio: CodecTypes['pg/text@1']['output'] | null;
      readonly finalizadaEm: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly hashTokenAcesso: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly iniciadaEm: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly instanciaId: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly status:
        'rascunho' | 'em_andamento' | 'pausada' | 'concluida' | 'cancelada' | 'falhou';
    };
    readonly campanha_contato: {
      readonly campanhaId: CodecTypes['pg/int4@1']['output'];
      readonly contatoId: CodecTypes['pg/int4@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly finalizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly iniciadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly status: 'pendente' | 'processando' | 'concluido' | 'parcial' | 'falhou';
    };
    readonly contato: {
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'] | null;
      readonly telefone: CodecTypes['pg/text@1']['output'];
    };
    readonly instancia: {
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly idNumeroTelefone: CodecTypes['pg/text@1']['output'];
      readonly limiteDiarioContatos: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly token: CodecTypes['pg/text@1']['output'];
      readonly usuarioUzapi: CodecTypes['pg/text@1']['output'];
    };
    readonly mensagem: {
      readonly campanhaId: CodecTypes['pg/int4@1']['output'];
      readonly criadaEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly posicao: CodecTypes['pg/int4@1']['output'];
      readonly texto: CodecTypes['pg/text@1']['output'] | null;
      readonly tipo: 'texto' | 'imagem' | 'audio';
      readonly urlMidia: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly resultado_mensagem: {
      readonly campanhaContatoId: CodecTypes['pg/int4@1']['output'];
      readonly criadaEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly enviadaEm: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly erro: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly idFila: CodecTypes['pg/text@1']['output'] | null;
      readonly idMensagem: CodecTypes['pg/text@1']['output'] | null;
      readonly mensagemId: CodecTypes['pg/int4@1']['output'];
      readonly status: 'pendente' | 'sucesso' | 'falhou';
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly campanha: {
      readonly criadaEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly emailRelatorio: CodecTypes['pg/text@1']['input'] | null;
      readonly finalizadaEm: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly hashTokenAcesso: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly iniciadaEm: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly instanciaId: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly status:
        'rascunho' | 'em_andamento' | 'pausada' | 'concluida' | 'cancelada' | 'falhou';
    };
    readonly campanha_contato: {
      readonly campanhaId: CodecTypes['pg/int4@1']['input'];
      readonly contatoId: CodecTypes['pg/int4@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly finalizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly iniciadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly status: 'pendente' | 'processando' | 'concluido' | 'parcial' | 'falhou';
    };
    readonly contato: {
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'] | null;
      readonly telefone: CodecTypes['pg/text@1']['input'];
    };
    readonly instancia: {
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly idNumeroTelefone: CodecTypes['pg/text@1']['input'];
      readonly limiteDiarioContatos: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly token: CodecTypes['pg/text@1']['input'];
      readonly usuarioUzapi: CodecTypes['pg/text@1']['input'];
    };
    readonly mensagem: {
      readonly campanhaId: CodecTypes['pg/int4@1']['input'];
      readonly criadaEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly posicao: CodecTypes['pg/int4@1']['input'];
      readonly texto: CodecTypes['pg/text@1']['input'] | null;
      readonly tipo: 'texto' | 'imagem' | 'audio';
      readonly urlMidia: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly resultado_mensagem: {
      readonly campanhaContatoId: CodecTypes['pg/int4@1']['input'];
      readonly criadaEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly enviadaEm: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly erro: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly idFila: CodecTypes['pg/text@1']['input'] | null;
      readonly idMensagem: CodecTypes['pg/text@1']['input'] | null;
      readonly mensagemId: CodecTypes['pg/int4@1']['input'];
      readonly status: 'pendente' | 'sucesso' | 'falhou';
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly campanha: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly instanciaId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly emailRelatorio: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'rascunho'>;
                  };
                };
                readonly hashTokenAcesso: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly iniciadaEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly finalizadaEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly criadaEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'campanha_instanciaId_idx_00db4b25';
                  readonly prefix: 'campanha_instanciaId_idx';
                  readonly columns: readonly ['instanciaId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'campanha_status_idx_e98638ab';
                  readonly prefix: 'campanha_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'campanha';
                    readonly columns: readonly ['instanciaId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'instancia';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly campanha_contato: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly campanhaId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly contatoId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'pendente'>;
                  };
                };
                readonly iniciadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly finalizadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['campanhaId', 'contatoId'] }];
              indexes: readonly [
                {
                  readonly name: 'campanha_contato_campanhaId_idx_6cd07fa5';
                  readonly prefix: 'campanha_contato_campanhaId_idx';
                  readonly columns: readonly ['campanhaId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'campanha_contato_contatoId_idx_55ea5573';
                  readonly prefix: 'campanha_contato_contatoId_idx';
                  readonly columns: readonly ['contatoId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'campanha_contato_status_idx_e98638ab';
                  readonly prefix: 'campanha_contato_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'campanha_contato';
                    readonly columns: readonly ['campanhaId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'campanha';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'campanha_contato';
                    readonly columns: readonly ['contatoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'contato';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly contato: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly telefone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'contato_telefone_idx_15d68930';
                  readonly prefix: 'contato_telefone_idx';
                  readonly columns: readonly ['telefone'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly instancia: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly usuarioUzapi: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly token: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly idNumeroTelefone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly limiteDiarioContatos: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 250>;
                  };
                };
                readonly ativo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly atualizadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['idNumeroTelefone'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly mensagem: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly campanhaId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly posicao: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly tipo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly texto: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly urlMidia: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly criadaEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['campanhaId', 'posicao'] }];
              indexes: readonly [
                {
                  readonly name: 'mensagem_campanhaId_idx_6cd07fa5';
                  readonly prefix: 'mensagem_campanhaId_idx';
                  readonly columns: readonly ['campanhaId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'mensagem';
                    readonly columns: readonly ['campanhaId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'campanha';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly resultado_mensagem: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly mensagemId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly campanhaContatoId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'pendente'>;
                  };
                };
                readonly idFila: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly idMensagem: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly erro: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly enviadaEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly criadaEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['mensagemId', 'campanhaContatoId'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'resultado_mensagem_mensagemId_idx_fa67b8b9';
                  readonly prefix: 'resultado_mensagem_mensagemId_idx';
                  readonly columns: readonly ['mensagemId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'resultado_mensagem_campanhaContatoId_idx_8a35d7f8';
                  readonly prefix: 'resultado_mensagem_campanhaContatoId_idx';
                  readonly columns: readonly ['campanhaContatoId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'resultado_mensagem_status_idx_e98638ab';
                  readonly prefix: 'resultado_mensagem_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'resultado_mensagem';
                    readonly columns: readonly ['mensagemId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'mensagem';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'resultado_mensagem';
                    readonly columns: readonly ['campanhaContatoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'campanha_contato';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly StatusCampanha: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'rascunho',
                'em_andamento',
                'pausada',
                'concluida',
                'cancelada',
                'falhou',
              ];
            };
            readonly StatusContatoCampanha: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'pendente',
                'processando',
                'concluido',
                'parcial',
                'falhou',
              ];
            };
            readonly StatusMensagem: {
              readonly kind: 'valueSet';
              readonly values: readonly ['pendente', 'sucesso', 'falhou'];
            };
            readonly TipoMensagem: {
              readonly kind: 'valueSet';
              readonly values: readonly ['texto', 'imagem', 'audio'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly instancia: { readonly namespace: 'public' & NamespaceId; readonly model: 'Instancia' };
    readonly campanha: { readonly namespace: 'public' & NamespaceId; readonly model: 'Campanha' };
    readonly contato: { readonly namespace: 'public' & NamespaceId; readonly model: 'Contato' };
    readonly campanha_contato: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'CampanhaContato';
    };
    readonly mensagem: { readonly namespace: 'public' & NamespaceId; readonly model: 'Mensagem' };
    readonly resultado_mensagem: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ResultadoMensagem';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Campanha: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly instanciaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly emailRelatorio: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly hashTokenAcesso: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly iniciadaEm: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly finalizadaEm: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly criadaEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly contatos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'CampanhaContato';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['campanhaId'];
                };
              };
              readonly instancia: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Instancia';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['instanciaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly mensagens: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Mensagem';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['campanhaId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'campanha';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly instanciaId: { readonly column: 'instanciaId' };
                readonly nome: { readonly column: 'nome' };
                readonly emailRelatorio: { readonly column: 'emailRelatorio' };
                readonly status: { readonly column: 'status' };
                readonly hashTokenAcesso: { readonly column: 'hashTokenAcesso' };
                readonly iniciadaEm: { readonly column: 'iniciadaEm' };
                readonly finalizadaEm: { readonly column: 'finalizadaEm' };
                readonly criadaEm: { readonly column: 'criadaEm' };
              };
            };
          };
          readonly CampanhaContato: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly campanhaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly contatoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly iniciadoEm: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly finalizadoEm: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly campanha: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Campanha';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['campanhaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly contato: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Contato';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['contatoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly resultados: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ResultadoMensagem';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['campanhaContatoId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'campanha_contato';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly campanhaId: { readonly column: 'campanhaId' };
                readonly contatoId: { readonly column: 'contatoId' };
                readonly status: { readonly column: 'status' };
                readonly iniciadoEm: { readonly column: 'iniciadoEm' };
                readonly finalizadoEm: { readonly column: 'finalizadoEm' };
                readonly criadoEm: { readonly column: 'criadoEm' };
              };
            };
          };
          readonly Contato: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly telefone: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nome: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly campanhas: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'CampanhaContato';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['contatoId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'contato';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly telefone: { readonly column: 'telefone' };
                readonly nome: { readonly column: 'nome' };
                readonly criadoEm: { readonly column: 'criadoEm' };
              };
            };
          };
          readonly Instancia: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly usuarioUzapi: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly token: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly idNumeroTelefone: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly limiteDiarioContatos: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly ativo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly atualizadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly campanhas: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Campanha';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['instanciaId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'instancia';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
                readonly usuarioUzapi: { readonly column: 'usuarioUzapi' };
                readonly token: { readonly column: 'token' };
                readonly idNumeroTelefone: { readonly column: 'idNumeroTelefone' };
                readonly limiteDiarioContatos: { readonly column: 'limiteDiarioContatos' };
                readonly ativo: { readonly column: 'ativo' };
                readonly criadoEm: { readonly column: 'criadoEm' };
                readonly atualizadoEm: { readonly column: 'atualizadoEm' };
              };
            };
          };
          readonly Mensagem: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly campanhaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly posicao: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly tipo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly texto: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly urlMidia: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly criadaEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly campanha: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Campanha';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['campanhaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly resultados: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ResultadoMensagem';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['mensagemId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'mensagem';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly campanhaId: { readonly column: 'campanhaId' };
                readonly posicao: { readonly column: 'posicao' };
                readonly tipo: { readonly column: 'tipo' };
                readonly texto: { readonly column: 'texto' };
                readonly urlMidia: { readonly column: 'urlMidia' };
                readonly criadaEm: { readonly column: 'criadaEm' };
              };
            };
          };
          readonly ResultadoMensagem: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly mensagemId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly campanhaContatoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly idFila: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly idMensagem: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly erro: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly enviadaEm: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly criadaEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly campanhaContato: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'CampanhaContato';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['campanhaContatoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly mensagem: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Mensagem';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['mensagemId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'resultado_mensagem';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly mensagemId: { readonly column: 'mensagemId' };
                readonly campanhaContatoId: { readonly column: 'campanhaContatoId' };
                readonly status: { readonly column: 'status' };
                readonly idFila: { readonly column: 'idFila' };
                readonly idMensagem: { readonly column: 'idMensagem' };
                readonly erro: { readonly column: 'erro' };
                readonly enviadaEm: { readonly column: 'enviadaEm' };
                readonly criadaEm: { readonly column: 'criadaEm' };
              };
            };
          };
        };
        readonly enum: {
          readonly StatusCampanha: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'RASCUNHO'; readonly value: 'rascunho' },
              { readonly name: 'EM_ANDAMENTO'; readonly value: 'em_andamento' },
              { readonly name: 'PAUSADA'; readonly value: 'pausada' },
              { readonly name: 'CONCLUIDA'; readonly value: 'concluida' },
              { readonly name: 'CANCELADA'; readonly value: 'cancelada' },
              { readonly name: 'FALHOU'; readonly value: 'falhou' },
            ];
          };
          readonly StatusContatoCampanha: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDENTE'; readonly value: 'pendente' },
              { readonly name: 'PROCESSANDO'; readonly value: 'processando' },
              { readonly name: 'CONCLUIDO'; readonly value: 'concluido' },
              { readonly name: 'PARCIAL'; readonly value: 'parcial' },
              { readonly name: 'FALHOU'; readonly value: 'falhou' },
            ];
          };
          readonly TipoMensagem: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'TEXTO'; readonly value: 'texto' },
              { readonly name: 'IMAGEM'; readonly value: 'imagem' },
              { readonly name: 'AUDIO'; readonly value: 'audio' },
            ];
          };
          readonly StatusMensagem: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDENTE'; readonly value: 'pendente' },
              { readonly name: 'SUCESSO'; readonly value: 'sucesso' },
              { readonly name: 'FALHOU'; readonly value: 'falhou' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
